# Generated by Django 2.2.24 on 2026-03-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='news',
            field=models.CharField(max_length=1000),
        ),
    ]
